server:
  port: 48080

--- #################### 数据库相关配置 ####################
spring:
  # 数据源配置项
  datasource:
    dynamic: # 多数据源配置
      primary: master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/mini_app_houduan?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: root
          password: zss200417
          driver-class-name: com.mysql.cj.jdbc.Driver  # 加上这个！
        slave: # 模拟从库
          lazy: true # 开启懒加载，保证启动速度
          url: jdbc:mysql://localhost:3306/mini_app_houduan?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: root
          password: zss200417
          driver-class-name: com.mysql.cj.jdbc.Driver  # 加上这个！

  # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
  data:
    redis:
      host: 127.0.0.1 # 地址
      port: 6379 # 端口
      database: 0 # 数据库索引
#    password: dev # 密码，建议生产环境开启

--- #################### 定时任务相关配置 ####################

--- #################### 消息队列相关 ####################


--- #################### 服务保障相关配置 ####################

--- #################### 监控相关配置 ####################

--- #################### 微信公众号、小程序相关配置 ####################
wx:
  miniapp:
    appid: wx60221e34e015df20
    secret: 4485494f37197bfad4e0104e42b95236

--- #################### 后端配置 ####################
hd:
  sms-code:
    expire-times: 9999d
    send-frequency: 1s #测试使用todo
    send-maximum-quantity-per-day: 9999
    begin-code: 1000 # 这里配置 9999 的原因是，测试方便。
    end-code: 9999 # 这里配置 9999 的原因是，测试方便。

justauth:
  enabled: true
  type:
    # noinspection SpringBootApplicationYaml
    WECHAT_MINI_PROGRAM: # 微信小程序
      client-id: ${wx.miniapp.appid}
      client-secret: ${wx.miniapp.secret}
      ignore-check-redirect-uri: true
      ignore-check-state: true # 微信小程序，不会使用到 state，所以不进行校验
  cache:
    type: REDIS
    prefix: 'social_auth_state:' # 缓存前缀，目前只对 Redis 缓存生效，默认 JUSTAUTH::STATE::
    timeout: 24h # 超时时长，目前只对 Redis 缓存生效，默认 3 分钟
logging:
  level:
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE #显示所有HTTPRequest
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG