### config: http/env.json
### 请求 /login 接口 => 成功
POST {{appApi}}/member/auth/login
Content-Type: application/json
tenant-id: {{appTenantId}}

{
  "mobile": "15601691388",
  "password": "admin123"
}
### 请求 /send-sms-code 接口 => 成功
POST {{appApi}}/member/auth/send-sms-code
Content-Type: application/json
tenant-id: {{appTenantId}}

{
  "mobile": "13123057856",
  "scene": 1
}

### 请求 /sms-login 接口 => 成功
POST {{appApi}}/member/auth/sms-login
Content-Type: application/json
tenant-id: {{appTenantId}}
terminal: 30

{
  "mobile": "13123057856",
  "code": 3686
}
###

// code需要更改
### 请求 /social-login 接口 => 成功
POST {{appApi}}/member/auth/social-login
Content-Type: application/json
tenant-id: {{appTenantId}}

{
  "type": 34,
  "code": "0e1oc9000CTjFQ1oim200bhtb61oc90g",
  "state": "default"
}

### 请求 /refresh-token 接口 => 成功
POST {{appApi}}/member/auth/refresh-token?refreshToken=6a4956fe5f0e48e3bc74fbec97ba8b43
Content-Type: application/json

{

}

### 请求 /logout 接口 => 成功
POST {{appApi}}/member/auth/logout
Content-Type: application/json
Authorization: Bearer b82e85a0c42b4baebadb7a091ef2ffbd
tenant-id: {{appTenantId}}

