<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.iocoder.boot</groupId>
        <artifactId>mini-app-houduan</artifactId>
        <version>2026.v1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>module-infra</artifactId>
    <modelVersion>4.0.0</modelVersion>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description></description>
    <url></url>


    <dependencies>
    <!-- 模块相关 -->
        <!-- Web 相关 -->
        <dependency>
            <groupId>cn.iocoder.boot</groupId>
            <artifactId>spring-security</artifactId>
        </dependency>
        <!-- DB 相关 -->
        <dependency>
            <groupId>cn.iocoder.boot</groupId>
            <artifactId>mybatis</artifactId>
        </dependency>
    <!-- 三方云服务相关 -->
        <dependency>
            <groupId>commons-net</groupId>
            <artifactId>commons-net</artifactId> <!-- 文件客户端：解决 ftp 连接 -->
        </dependency>
        <dependency>
            <groupId>com.github.mwiede</groupId>
            <artifactId>jsch</artifactId> <!-- 文件客户端：解决 sftp 连接 -->
        </dependency>
        <!-- 文件客户端：解决阿里云、腾讯云、minio 等 S3 连接 -->
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.tika</groupId>
            <artifactId>tika-core</artifactId> <!-- 文件客户端：文件类型的识别 -->
        </dependency>
    </dependencies>

</project>
