<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<groupId>cn.iocoder.boot</groupId>
		<artifactId>framework</artifactId>
		<version>2026.v1.0.0</version>
	</parent>
	<!--模块信息-->
	<modelVersion>4.0.0</modelVersion>
	<artifactId>spring-web</artifactId>
	<packaging>jar</packaging>
	<name>${project.artifactId}</name>
	<description>
		1. security：用户的认证、权限的校验，实现「谁」可以做「什么事」
		2. operatelog：操作日志，实现「谁」在「什么时间」对「什么」做了「什么事」
	</description>
	<url></url>
	<!--模块依赖-->
	<dependencies>
		<dependency>
			<groupId>cn.iocoder.boot</groupId>
			<artifactId>common</artifactId>
		</dependency>
		<!--核心依赖-->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<!-- 工具类相关 -->
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
		</dependency>
		<dependency>
			<groupId>jakarta.validation</groupId>
			<artifactId>jakarta.validation-api</artifactId>
		</dependency>

	</dependencies>

</project>
