<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.iocoder.boot</groupId>
        <artifactId>framework</artifactId>
        <version>2026.v1.0.0</version>
    </parent>
    <!--模块信息-->
    <modelVersion>4.0.0</modelVersion>
    <artifactId>job</artifactId>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>
    <description>
        1. 定时任务，基于 Quartz 拓展
        2. 异步任务，基于 Spring Async 拓展
    </description>
    <url></url>
    <!--本模块依赖-->
    <dependencies>
        <dependency>
            <groupId>cn.iocoder.boot</groupId>
            <artifactId>common</artifactId>
        </dependency>

    <!-- 工具类依赖 -->
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-quartz</artifactId>
        </dependency>
    </dependencies>


</project>
